StudentMVC/Controllers/AttendanceController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using StudentMVC.Data;
using StudentMVC.Models;

// using StudentMVC.Services;

namespace StudentMVC.Controllers;

public class AttendanceController : Controller
{
    private readonly AppDbContext _context;

    public AttendanceController(AppDbContext context)
    {
        _context = context;
    }

    public async Task<IActionResult> Index()
    {
        var attendances = await _context
            .Attendances.Include(a => a.Student)
            .OrderByDescending(a => a.Date)
            .ThenByDescending(a => a.Time)
            .ToListAsync();

        return View(attendances);
    }

    // GET: Attendance/Create/{studentId}
    [HttpGet]
    public async Task<IActionResult> Create(int studentId)
    {
        var student = await _context.Students.FindAsync(studentId);
        if (student == null)
        {
            TempData["ErrorMessage"] = "ID Siswa tidak ditemukan";
            return RedirectToAction("Index", "Student");
        }

        var attendance = new Attendance
        {
            StudentId = studentId,
            Student = student,
            Date = DateTime.Now,
            Time = DateTime.Now,
        };
        return View(attendance);
    }

    // POST: Attendance/Create/{studentId}
    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(Attendance attendance)
    {
        var student = _context.Students.Find(attendance.StudentId);
        if (student == null)
        {
            TempData["ErrorMessage"] = "ID Siswa tidak ditemukan";
            return RedirectToAction("Index", "Student");
        }

        attendance.Student = student;

        if (!ModelState.IsValid)
        {
            TempData["ErrorMessage"] = "Data Presensi tidak valid";
            return View(attendance);
        }
        _context.Add(attendance);
        await _context.SaveChangesAsync();
        TempData["SuccessMessage"] = "Presensi berhasil disimpan";
        return RedirectToAction(nameof(Index));
    }
}

StudentMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - StudentMVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/StudentMVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <partial name="_NavigationMenu" />
    </header>
    <div class="container">
        <main role="main" class="pb-3">
						@await Html.PartialAsync("_Notification")
						
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - StudentMVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

StudentMVC/Views/Shared/_NavigationMenu.cshtml
<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
	<div class="container-fluid">
		<a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">StudentMVC</a>
		<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
		<div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
			<ul class="navbar-nav flex-grow-1 gap-2">
				<li class="nav-item nav-pills">
					<a class="nav-link" asp-controller="Home" asp-action="Index">Beranda</a>
    		</li>
    		<li class="nav-item nav-pills">
        	<a class="nav-link" asp-controller="Student" asp-action="Index">Siswa</a>
    		</li>
    		<li class="nav-item nav-pills">
        	<a class="nav-link" asp-controller="Attendance" asp-action="Index">Presensi</a>
				</li>
				<li class="nav-item nav-pills">
        	<a class="nav-link" asp-controller="Course" asp-action="Index">Kursus</a>
				</li>
			</ul>
		</div>
	</div>
</nav>

StudentMVC/Views/Shared/_Notification.cshtml
@if (TempData["SuccessMessage"] != null)
{
    <div class="alert alert-success alert-dismissible fade show" role="alert">
        @TempData["SuccessMessage"]
        <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
    </div>
}

@if (TempData["ErrorMessage"] != null)
{
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        @TempData["ErrorMessage"]
        <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
    </div>
}