paracommerce/Controllers/MarketController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using paracommerce.Data;

namespace paracommerce.Controllers;

public class MarketController : Controller
{
    private readonly AppDbContext _context;

    public MarketController(AppDbContext context)
    {
        _context = context;
    }

    public async Task<IActionResult> Index(string searchName)
    {
        var products = await _context
            .Products.Where(s =>
                string.IsNullOrEmpty(searchName) || (s.Name != null && s.Name.Contains(searchName))
            )
            .ToListAsync();

        if (!products.Any())
        {
            ViewBag.Message = "Belum ada produk yang dapat ditampilkan.";
        }
        return View(products);
    }
}

paracommerce/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ParaCommerce</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/paracommerce.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <partial name="_NavigationMenu" />
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - paracommerce - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

paracommerce/Views/Shared/_NavigationMenu.cshtml
<nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
	<div class="container-fluid">
		<a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ParaCommerce</a>
		<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
		<div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
			<ul class="navbar-nav flex-grow-1 gap-2">
				<li class="nav-item nav-pills">
					<a class="nav-link" asp-controller="Market" asp-action="Index">Market</a>
    			</li>
    			<li class="nav-item nav-pills">
        			<a class="nav-link" asp-controller="Product" asp-action="Index">Admin Panel</a>
    			</li>
			</ul>
		</div>
	</div>
</nav>